/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#4cd6ff",
        "tertiary-fixed": "#b7eaff",
        "background": "#10131a",
        "on-primary-fixed-variant": "#0035be",
        "on-tertiary-fixed-variant": "#004e60",
        "secondary-fixed": "#e9ddff",
        "surface-bright": "#363940",
        "primary": "#b8c3ff",
        "outline": "#8e90a2",
        "on-surface-variant": "#c4c5d9",
        "secondary-fixed-dim": "#d1bcff",
        "inverse-primary": "#124af0",
        "surface-container-low": "#191c22",
        "on-secondary": "#3c0090",
        "on-secondary-fixed": "#23005b",
        "on-error": "#690005",
        "surface-container-lowest": "#0b0e14",
        "on-primary-container": "#efefff",
        "on-tertiary": "#003543",
        "on-secondary-container": "#ddcdff",
        "inverse-on-surface": "#2e3037",
        "primary-fixed": "#dde1ff",
        "surface-container-high": "#272a31",
        "outline-variant": "#434656",
        "on-tertiary-container": "#dbf4ff",
        "tertiary-container": "#007792",
        "surface-variant": "#32353c",
        "on-primary-fixed": "#001356",
        "surface-dim": "#10131a",
        "tertiary": "#4cd6ff",
        "surface-container-highest": "#32353c",
        "on-primary": "#002388",
        "on-tertiary-fixed": "#001f28",
        "on-background": "#e1e2eb",
        "primary-fixed-dim": "#b8c3ff",
        "error": "#ffb4ab",
        "secondary": "#d1bcff",
        "secondary-container": "#7000ff",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#e1e2eb",
        "on-secondary-fixed-variant": "#5700c9",
        "primary-container": "#2e5bff",
        "error-container": "#93000a",
        "surface-container": "#1d2026",
        "surface-tint": "#b8c3ff",
        "surface": "#10131a",
        "on-surface": "#e1e2eb"
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "sm": "0.25rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "container-max-width": "1280px",
        "margin-desktop": "64px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "unit": "4px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Vazirmatn"],
        "body-lg": ["Vazirmatn"],
        "label-sm": ["Vazirmatn"],
        "label-md": ["Vazirmatn"],
        "headline-lg": ["Vazirmatn"],
        "body-md": ["Vazirmatn"],
        "headline-md": ["Vazirmatn"]
      },
      fontSize: {
        "headline-lg-mobile": ["30px", { "lineHeight": "42px", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "32px", "fontWeight": "400" }],
        "label-sm": ["13px", { "lineHeight": "18px", "fontWeight": "500" }],
        "label-md": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
        "headline-lg": ["40px", { "lineHeight": "56px", "letterSpacing": "0", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-md": ["28px", { "lineHeight": "40px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
